joint_1_controller:
  type: "position_controllers/JointPositionController"
  joint: joint1
joint_2_controller:
  type: "position_controllers/JointPositionController"
  joint: joint2

joint_3_controller:
  type: "position_controllers/JointPositionController"
  joint: joint3
  
joint_4_controller:
  type: "position_controllers/JointPositionController"
  joint: joint4
